#pragma once
#include "Vulkan_GLFW.hpp"

extern PFN_vkCreateAccelerationStructureKHR rt_vkCreateAccelerationStructureKHR;
extern PFN_vkDestroyAccelerationStructureKHR rt_vkDestroyAccelerationStructureKHR;
extern PFN_vkGetAccelerationStructureBuildSizesKHR rt_vkGetAccelerationStructureBuildSizesKHR;
extern PFN_vkCmdBuildAccelerationStructuresKHR rt_vkCmdBuildAccelerationStructuresKHR;
extern PFN_vkGetAccelerationStructureDeviceAddressKHR rt_vkGetAccelerationStructureDeviceAddressKHR;

extern PFN_vkGetBufferDeviceAddressKHR rt_vkGetBufferDeviceAddressKHR;
extern PFN_vkCreateRayTracingPipelinesKHR rt_vkCreateRayTracingPipelinesKHR;
extern PFN_vkGetRayTracingShaderGroupHandlesKHR rt_vkGetRayTracingShaderGroupHandlesKHR;
extern PFN_vkCmdTraceRaysKHR rt_vkCmdTraceRaysKHR;

extern PFN_vkSetDebugUtilsObjectNameEXT debug_vkSetDebugUtilsObjectNameEXT;
extern PFN_vkCmdBeginDebugUtilsLabelEXT debug_vkCmdBeginDebugUtilsLabelEXT;
extern PFN_vkCmdEndDebugUtilsLabelEXT debug_vkCmdEndDebugUtilsLabelEXT;

void loadExtensionFunctions(VkDevice device);